openapi: 3.0.0
info:
  title: KOA Rest Documentation
  version: 1.0.0
  description: RESTful API documentation

servers:
  - url: http://localhost:3000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []